#ifndef NETCONF_GENERATED_H
#define NETCONF_GENERATED_H

enum xml_tag_type {
  XML_TAG_TYPE_NONE,
  XML_TAG_TYPE_ADDITIONAL_TEXT,
  XML_TAG_TYPE_ADDRESS,
  XML_TAG_TYPE_ALARM,
  XML_TAG_TYPE_ALARM_TYPE,
  XML_TAG_TYPE_ALT_CUST_VERSION,
  XML_TAG_TYPE_ALT_VERSION,
  XML_TAG_TYPE_BANDWIDTH,
  XML_TAG_TYPE_CAPABILITIES,
  XML_TAG_TYPE_CAPABILITY,
  XML_TAG_TYPE_CATEGORY,
  XML_TAG_TYPE_CIR,
  XML_TAG_TYPE_CLEI,
  XML_TAG_TYPE_CONFIG_FILE_COPIED,
  XML_TAG_TYPE_COUNTERS,
  XML_TAG_TYPE_CPU_PERCENT_UTILIZATION,
  XML_TAG_TYPE_CURR_COMMITTED,
  XML_TAG_TYPE_CURR_CUST_VERSION,
  XML_TAG_TYPE_CURR_VERSION,
  XML_TAG_TYPE_C_VLAN,
  XML_TAG_TYPE_C_VLAN_ID,
  XML_TAG_TYPE_CYCLIC_SLEEP_TIME,
  XML_TAG_TYPE_DATA,
  XML_TAG_TYPE_DATA_POWER_SHEDDING_TIMEOUT,
  XML_TAG_TYPE_DBA_PRIORITY,
  XML_TAG_TYPE_DESCRIPTION,
  XML_TAG_TYPE_DETAIL,
  XML_TAG_TYPE_DETAILS,
  XML_TAG_TYPE_DEVICE_SEQUENCE_NUMBER,
  XML_TAG_TYPE_DHCP_LEASE_ESTABLISHMENT,
  XML_TAG_TYPE_DHCP_LEASE_TERMINATION,
  XML_TAG_TYPE_DIRECTION,
  XML_TAG_TYPE_DOWNSTREAM_BIP8_ERR_SEC,
  XML_TAG_TYPE_DOWNSTREAM_BIP8_SEVERELY_ERR_SEC,
  XML_TAG_TYPE_DOWNSTREAM_BIP8_UNAVAIL_SEC,
  XML_TAG_TYPE_DOWNSTREAM_BIP_ERRORS,
  XML_TAG_TYPE_DOWNSTREAM_FEC_CORRECTED_BYTES,
  XML_TAG_TYPE_DOWNSTREAM_FEC_CORRECTED_CODE_WORDS,
  XML_TAG_TYPE_DOWNSTREAM_FEC_SEC,
  XML_TAG_TYPE_DOWNSTREAM_FEC_TOTAL_CODE_WORDS,
  XML_TAG_TYPE_DOWNSTREAM_FEC_UNCORRECTED_CODE_WORDS,
  XML_TAG_TYPE_DOWNSTREAM_OCTETS,
  XML_TAG_TYPE_DOWNSTREAM_PON_RATE,
  XML_TAG_TYPE_DOZE_TIME,
  XML_TAG_TYPE_DS_BER_MONITOR,
  XML_TAG_TYPE_DS_SDBER_RATE,
  XML_TAG_TYPE_EIR,
  XML_TAG_TYPE_ENERGY_CONSUMED,
  XML_TAG_TYPE_EQUIPMENT_TYPE,
  XML_TAG_TYPE_ERRORS_IN_OPERATIONS,
  XML_TAG_TYPE_EVENTTIME,
  XML_TAG_TYPE_FLASH_AVAILABLE_AMOUNT,
  XML_TAG_TYPE_FLASH_MEMORY_PERFORMANCE,
  XML_TAG_TYPE_FLASH_UTILIZATION,
  XML_TAG_TYPE_GREEN_MAXIMUM_DROP_THRESHOLD,
  XML_TAG_TYPE_GREEN_MINIMUM_DROP_THRESHOLD,
  XML_TAG_TYPE_GREEN_PACKET_DROP_PROBABILITY,
  XML_TAG_TYPE_HELLO,
  XML_TAG_TYPE_HW_FAILURE_EVENT,
  XML_TAG_TYPE_ID,
  XML_TAG_TYPE_INDEX,
  XML_TAG_TYPE_INSTANCE_ID,
  XML_TAG_TYPE_INTERNAL_PON_DEVICE,
  XML_TAG_TYPE_LAST_DOWNSTREAM_PERCENTAGE,
  XML_TAG_TYPE_LAST_UPSTREAM_PERCENTAGE,
  XML_TAG_TYPE_LATEST_RESTART_REASON,
  XML_TAG_TYPE_LINKAGE,
  XML_TAG_TYPE_LINKED_BY,
  XML_TAG_TYPE_LINKED_PON,
  XML_TAG_TYPE_LOGICAL_PORT,
  XML_TAG_TYPE_LOW_RX_OPT_PWR_NE,
  XML_TAG_TYPE_MAX_SIZE,
  XML_TAG_TYPE_MFG_SERIAL_NUMBER,
  XML_TAG_TYPE_MODEL,
  XML_TAG_TYPE_MTA_MAC_ADDR,
  XML_TAG_TYPE_NAME,
  XML_TAG_TYPE_NE_OPT_SIGNAL_LEVEL,
  XML_TAG_TYPE_NEXT_STATUS_SNAPSHOT_INDEX,
  XML_TAG_TYPE_NOTIFICATION,
  XML_TAG_TYPE_NTP_SERVER_REACHABILITY,
  XML_TAG_TYPE_NUMBER_OF_VALID_STATUS_SNAPSHOTS,
  XML_TAG_TYPE_OK,
  XML_TAG_TYPE_ONT,
  XML_TAG_TYPE_ONT_ARRIVAL,
  XML_TAG_TYPE_ONT_COUNTERS,
  XML_TAG_TYPE_ONT_DEPARTURE,
  XML_TAG_TYPE_ONT_DS_SDBER,
  XML_TAG_TYPE_ONT_DYING_GASP,
  XML_TAG_TYPE_ONT_ETH_DOWN,
  XML_TAG_TYPE_ONT_ID,
  XML_TAG_TYPE_ONT_MISSING,
  XML_TAG_TYPE_ONU_ID,
  XML_TAG_TYPE_ONU_MAC_ADDR,
  XML_TAG_TYPE_OPER_STATE,
  XML_TAG_TYPE_OPT_SIGNAL_LEVEL,
  XML_TAG_TYPE_PERCEIVED_SEVERITY,
  XML_TAG_TYPE_PHYS_PON_PORT,
  XML_TAG_TYPE_PHYS_PON_SHELF,
  XML_TAG_TYPE_PHYS_PON_SLOT,
  XML_TAG_TYPE_POLICY,
  XML_TAG_TYPE_PON,
  XML_TAG_TYPE_PON_COS,
  XML_TAG_TYPE_PON_COS_AIR,
  XML_TAG_TYPE_PON_COS_EIR,
  XML_TAG_TYPE_PON_DEVICE,
  XML_TAG_TYPE_PON_QOS,
  XML_TAG_TYPE_PON_US_COS_STATUS,
  XML_TAG_TYPE_PORT,
  XML_TAG_TYPE_PREV_SEVERITY,
  XML_TAG_TYPE_PRIMARY_ELEMENT,
  XML_TAG_TYPE_PROBABLE_CAUSE,
  XML_TAG_TYPE_PRODUCT_CODE,
  XML_TAG_TYPE_QOS,
  XML_TAG_TYPE_QUEUE,
  XML_TAG_TYPE_QUEUE_DEPTH,
  XML_TAG_TYPE_QUEUE_DROP_AVERAGING_COEFFICIENT,
  XML_TAG_TYPE_RAM_AVAILABLE_AMOUNT,
  XML_TAG_TYPE_RAM_UTILIZATION,
  XML_TAG_TYPE_RANGE_LENGTH,
  XML_TAG_TYPE_RANGE_TIME,
  XML_TAG_TYPE_REFERENCE_COUNT,
  XML_TAG_TYPE_REG_ID,
  XML_TAG_TYPE_REPAIR_ACTION,
  XML_TAG_TYPE_RG_CONFIG_VERSION,
  XML_TAG_TYPE_RPC_REPLY,
  XML_TAG_TYPE_SERIAL_NUMBER,
  XML_TAG_TYPE_SERVICE_AFFECTING,
  XML_TAG_TYPE_SERVICE_IMPACTING,
  XML_TAG_TYPE_SERVICE_STATS_GROUP,
  XML_TAG_TYPE_SESSION_ID,
  XML_TAG_TYPE_SESSION_IP,
  XML_TAG_TYPE_SESSION_LOGIN,
  XML_TAG_TYPE_SESSION_MANAGER,
  XML_TAG_TYPE_SHELF_ID,
  XML_TAG_TYPE_SLOT_ID,
  XML_TAG_TYPE_SOFTWARE_ERRORS,
  XML_TAG_TYPE_STATUS,
  XML_TAG_TYPE_SYSTEM,
  XML_TAG_TYPE_T1_POWER_SHEDDING_TIMEOUT,
  XML_TAG_TYPE_TOTAL_NUMBER_OF_STATUS_SNAPSHOTS,
  XML_TAG_TYPE_TRANSFER_FAILED,
  XML_TAG_TYPE_TRANSFER_REQUESTED,
  XML_TAG_TYPE_TX_OPT_LEVEL,
  XML_TAG_TYPE_TYPE,
  XML_TAG_TYPE_UPGRADE_CLASS,
  XML_TAG_TYPE_UPSTREAM_BIP8_ERR_SEC,
  XML_TAG_TYPE_UPSTREAM_BIP8_SEVERELY_ERR_SEC,
  XML_TAG_TYPE_UPSTREAM_BIP8_UNAVAIL_SEC,
  XML_TAG_TYPE_UPSTREAM_BIP_ERRORS,
  XML_TAG_TYPE_UPSTREAM_FEC_CORRECTED_BYTES,
  XML_TAG_TYPE_UPSTREAM_FEC_CORRECTED_CODE_WORDS,
  XML_TAG_TYPE_UPSTREAM_FEC_SEC,
  XML_TAG_TYPE_UPSTREAM_FEC_TOTAL_CODE_WORDS,
  XML_TAG_TYPE_UPSTREAM_FEC_UNCORRECTED_CODE_WORDS,
  XML_TAG_TYPE_UPSTREAM_GEM_HEC_ERRORS,
  XML_TAG_TYPE_UPSTREAM_MISSED_BURSTS,
  XML_TAG_TYPE_UPSTREAM_MISSED_BURSTS_ERR_SEC,
  XML_TAG_TYPE_UPSTREAM_OCTETS,
  XML_TAG_TYPE_UPSTREAM_PON_RATE,
  XML_TAG_TYPE_UP_TIME,
  XML_TAG_TYPE_US_BER_MONITOR,
  XML_TAG_TYPE_USER_LOGIN,
  XML_TAG_TYPE_USER_LOGOUT,
  XML_TAG_TYPE_USER_NAME,
  XML_TAG_TYPE_US_SDBER_RATE,
  XML_TAG_TYPE_UTILIZATION_COUNTERS,
  XML_TAG_TYPE_VENDOR,
  XML_TAG_TYPE_VENDOR_ID,
  XML_TAG_TYPE_VIDEO_OVERLAY_POWER_SHEDDING_TIMEOUT,
  XML_TAG_TYPE_VIDEO_RETURN_POWER_SHEDDING_TIMEOUT,
  XML_TAG_TYPE_VLAN,
  XML_TAG_TYPE_VLAN_ID,
  XML_TAG_TYPE_VOICE_POWER_SHEDDING_TIMEOUT,
  XML_TAG_TYPE_VOIP_CONFIG_VERSION,
  XML_TAG_TYPE_WATCHFUL_SLEEP_TIME,
  XML_TAG_TYPE_WEIGHT,
  XML_TAG_TYPE_YELLOW_MAXIMUM_DROP_THRESHOLD,
  XML_TAG_TYPE_YELLOW_MINIMUM_DROP_THRESHOLD,
  XML_TAG_TYPE_YELLOW_PACKET_DROP_PROBABILITY,
};

// nx_parse
enum nx_enum {
  NX_ONT_MISSING,
  NX_DESCRIPTION,
  NX_PROBABLE_CAUSE,
  NX_DETAIL
};

struct nx_parse {
    char* name;
    enum nx_enum nx;
};

//static unsigned int
//hash_nx (register const char *str, register size_t len);

//struct nx_parse *
//in_word_set_nx (register const char *str, register size_t len);

// ns_xmlns_parse
enum nx_xmlns_enum {
  NX_XMLNS_ONT_MISSING,
  NX_XMLNS_DESCRIPTION,
  NX_XMLNS_PROBABLE_CAUSE,
  NX_XMLNS_DETAIL
};

struct nx_xmlns_parse {
    char* name;
    enum nx_xmlns_enum nx_xmlns;
};

static unsigned int
hash_nx_xmlns (register const char *str, register size_t len);

// nx_tree
enum nx_tree_enum {
  NX_TREE_ONT_MISSING,
  NX_TREE_DESCRIPTION,
  NX_TREE_PROBABLE_CAUSE,
  NX_TREE_DETAIL
};

/*
union Strings {
    char *string;
    char *strings[];
};
*/

struct nx_tree_parse {
    char* name;
    enum nx_tree_enum nx_tree;
/*
    enum cbor_actions action;
    // This string is empty or NULL if it is a direct match and there is no regex to do
    // Only the first element in each array will be used in that case, since there is
    // only one match (the entire string returned from libexpat)
    char *regex_match_string;
    char *keys[];
    enum cbor_types[];
*/
};

static unsigned int
hash_nx_tree (register const char *str, register size_t len);

struct nx_tree_parse *
in_word_set_nx_tree (register const char *str, register size_t len);

#endif //NETCONF_GENERATED_H
