/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: axos.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "axos.pb-c.h"
void   axos__ont_missing__init
                     (Axos__OntMissing         *message)
{
  static const Axos__OntMissing init_value = AXOS__ONT_MISSING__INIT;
  *message = init_value;
}
size_t axos__ont_missing__get_packed_size
                     (const Axos__OntMissing *message)
{
  assert(message->base.descriptor == &axos__ont_missing__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t axos__ont_missing__pack
                     (const Axos__OntMissing *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &axos__ont_missing__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t axos__ont_missing__pack_to_buffer
                     (const Axos__OntMissing *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &axos__ont_missing__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Axos__OntMissing *
       axos__ont_missing__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Axos__OntMissing *)
     protobuf_c_message_unpack (&axos__ont_missing__descriptor,
                                allocator, len, data);
}
void   axos__ont_missing__free_unpacked
                     (Axos__OntMissing *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &axos__ont_missing__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   axos__ont_ds_sdber__init
                     (Axos__OntDsSdber         *message)
{
  static const Axos__OntDsSdber init_value = AXOS__ONT_DS_SDBER__INIT;
  *message = init_value;
}
size_t axos__ont_ds_sdber__get_packed_size
                     (const Axos__OntDsSdber *message)
{
  assert(message->base.descriptor == &axos__ont_ds_sdber__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t axos__ont_ds_sdber__pack
                     (const Axos__OntDsSdber *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &axos__ont_ds_sdber__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t axos__ont_ds_sdber__pack_to_buffer
                     (const Axos__OntDsSdber *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &axos__ont_ds_sdber__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Axos__OntDsSdber *
       axos__ont_ds_sdber__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Axos__OntDsSdber *)
     protobuf_c_message_unpack (&axos__ont_ds_sdber__descriptor,
                                allocator, len, data);
}
void   axos__ont_ds_sdber__free_unpacked
                     (Axos__OntDsSdber *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &axos__ont_ds_sdber__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   axos__ont_us_sdber__init
                     (Axos__OntUsSdber         *message)
{
  static const Axos__OntUsSdber init_value = AXOS__ONT_US_SDBER__INIT;
  *message = init_value;
}
size_t axos__ont_us_sdber__get_packed_size
                     (const Axos__OntUsSdber *message)
{
  assert(message->base.descriptor == &axos__ont_us_sdber__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t axos__ont_us_sdber__pack
                     (const Axos__OntUsSdber *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &axos__ont_us_sdber__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t axos__ont_us_sdber__pack_to_buffer
                     (const Axos__OntUsSdber *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &axos__ont_us_sdber__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Axos__OntUsSdber *
       axos__ont_us_sdber__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Axos__OntUsSdber *)
     protobuf_c_message_unpack (&axos__ont_us_sdber__descriptor,
                                allocator, len, data);
}
void   axos__ont_us_sdber__free_unpacked
                     (Axos__OntUsSdber *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &axos__ont_us_sdber__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   axos__ont_arrival__init
                     (Axos__OntArrival         *message)
{
  static const Axos__OntArrival init_value = AXOS__ONT_ARRIVAL__INIT;
  *message = init_value;
}
size_t axos__ont_arrival__get_packed_size
                     (const Axos__OntArrival *message)
{
  assert(message->base.descriptor == &axos__ont_arrival__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t axos__ont_arrival__pack
                     (const Axos__OntArrival *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &axos__ont_arrival__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t axos__ont_arrival__pack_to_buffer
                     (const Axos__OntArrival *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &axos__ont_arrival__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Axos__OntArrival *
       axos__ont_arrival__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Axos__OntArrival *)
     protobuf_c_message_unpack (&axos__ont_arrival__descriptor,
                                allocator, len, data);
}
void   axos__ont_arrival__free_unpacked
                     (Axos__OntArrival *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &axos__ont_arrival__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   axos__ont_departure__init
                     (Axos__OntDeparture         *message)
{
  static const Axos__OntDeparture init_value = AXOS__ONT_DEPARTURE__INIT;
  *message = init_value;
}
size_t axos__ont_departure__get_packed_size
                     (const Axos__OntDeparture *message)
{
  assert(message->base.descriptor == &axos__ont_departure__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t axos__ont_departure__pack
                     (const Axos__OntDeparture *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &axos__ont_departure__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t axos__ont_departure__pack_to_buffer
                     (const Axos__OntDeparture *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &axos__ont_departure__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Axos__OntDeparture *
       axos__ont_departure__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Axos__OntDeparture *)
     protobuf_c_message_unpack (&axos__ont_departure__descriptor,
                                allocator, len, data);
}
void   axos__ont_departure__free_unpacked
                     (Axos__OntDeparture *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &axos__ont_departure__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   axos__user_login__init
                     (Axos__UserLogin         *message)
{
  static const Axos__UserLogin init_value = AXOS__USER_LOGIN__INIT;
  *message = init_value;
}
size_t axos__user_login__get_packed_size
                     (const Axos__UserLogin *message)
{
  assert(message->base.descriptor == &axos__user_login__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t axos__user_login__pack
                     (const Axos__UserLogin *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &axos__user_login__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t axos__user_login__pack_to_buffer
                     (const Axos__UserLogin *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &axos__user_login__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Axos__UserLogin *
       axos__user_login__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Axos__UserLogin *)
     protobuf_c_message_unpack (&axos__user_login__descriptor,
                                allocator, len, data);
}
void   axos__user_login__free_unpacked
                     (Axos__UserLogin *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &axos__user_login__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   axos__user_logout__init
                     (Axos__UserLogout         *message)
{
  static const Axos__UserLogout init_value = AXOS__USER_LOGOUT__INIT;
  *message = init_value;
}
size_t axos__user_logout__get_packed_size
                     (const Axos__UserLogout *message)
{
  assert(message->base.descriptor == &axos__user_logout__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t axos__user_logout__pack
                     (const Axos__UserLogout *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &axos__user_logout__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t axos__user_logout__pack_to_buffer
                     (const Axos__UserLogout *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &axos__user_logout__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Axos__UserLogout *
       axos__user_logout__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Axos__UserLogout *)
     protobuf_c_message_unpack (&axos__user_logout__descriptor,
                                allocator, len, data);
}
void   axos__user_logout__free_unpacked
                     (Axos__UserLogout *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &axos__user_logout__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   axos__ont_eth_down__init
                     (Axos__OntEthDown         *message)
{
  static const Axos__OntEthDown init_value = AXOS__ONT_ETH_DOWN__INIT;
  *message = init_value;
}
size_t axos__ont_eth_down__get_packed_size
                     (const Axos__OntEthDown *message)
{
  assert(message->base.descriptor == &axos__ont_eth_down__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t axos__ont_eth_down__pack
                     (const Axos__OntEthDown *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &axos__ont_eth_down__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t axos__ont_eth_down__pack_to_buffer
                     (const Axos__OntEthDown *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &axos__ont_eth_down__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Axos__OntEthDown *
       axos__ont_eth_down__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Axos__OntEthDown *)
     protobuf_c_message_unpack (&axos__ont_eth_down__descriptor,
                                allocator, len, data);
}
void   axos__ont_eth_down__free_unpacked
                     (Axos__OntEthDown *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &axos__ont_eth_down__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   axos__ont_eth_down_clear__init
                     (Axos__OntEthDownClear         *message)
{
  static const Axos__OntEthDownClear init_value = AXOS__ONT_ETH_DOWN_CLEAR__INIT;
  *message = init_value;
}
size_t axos__ont_eth_down_clear__get_packed_size
                     (const Axos__OntEthDownClear *message)
{
  assert(message->base.descriptor == &axos__ont_eth_down_clear__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t axos__ont_eth_down_clear__pack
                     (const Axos__OntEthDownClear *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &axos__ont_eth_down_clear__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t axos__ont_eth_down_clear__pack_to_buffer
                     (const Axos__OntEthDownClear *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &axos__ont_eth_down_clear__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Axos__OntEthDownClear *
       axos__ont_eth_down_clear__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Axos__OntEthDownClear *)
     protobuf_c_message_unpack (&axos__ont_eth_down_clear__descriptor,
                                allocator, len, data);
}
void   axos__ont_eth_down_clear__free_unpacked
                     (Axos__OntEthDownClear *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &axos__ont_eth_down_clear__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   axos__ont_dying_gasp__init
                     (Axos__OntDyingGasp         *message)
{
  static const Axos__OntDyingGasp init_value = AXOS__ONT_DYING_GASP__INIT;
  *message = init_value;
}
size_t axos__ont_dying_gasp__get_packed_size
                     (const Axos__OntDyingGasp *message)
{
  assert(message->base.descriptor == &axos__ont_dying_gasp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t axos__ont_dying_gasp__pack
                     (const Axos__OntDyingGasp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &axos__ont_dying_gasp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t axos__ont_dying_gasp__pack_to_buffer
                     (const Axos__OntDyingGasp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &axos__ont_dying_gasp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Axos__OntDyingGasp *
       axos__ont_dying_gasp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Axos__OntDyingGasp *)
     protobuf_c_message_unpack (&axos__ont_dying_gasp__descriptor,
                                allocator, len, data);
}
void   axos__ont_dying_gasp__free_unpacked
                     (Axos__OntDyingGasp *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &axos__ont_dying_gasp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   axos__ont_dying_gasp_clear__init
                     (Axos__OntDyingGaspClear         *message)
{
  static const Axos__OntDyingGaspClear init_value = AXOS__ONT_DYING_GASP_CLEAR__INIT;
  *message = init_value;
}
size_t axos__ont_dying_gasp_clear__get_packed_size
                     (const Axos__OntDyingGaspClear *message)
{
  assert(message->base.descriptor == &axos__ont_dying_gasp_clear__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t axos__ont_dying_gasp_clear__pack
                     (const Axos__OntDyingGaspClear *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &axos__ont_dying_gasp_clear__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t axos__ont_dying_gasp_clear__pack_to_buffer
                     (const Axos__OntDyingGaspClear *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &axos__ont_dying_gasp_clear__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Axos__OntDyingGaspClear *
       axos__ont_dying_gasp_clear__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Axos__OntDyingGaspClear *)
     protobuf_c_message_unpack (&axos__ont_dying_gasp_clear__descriptor,
                                allocator, len, data);
}
void   axos__ont_dying_gasp_clear__free_unpacked
                     (Axos__OntDyingGaspClear *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &axos__ont_dying_gasp_clear__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   axos__low_rx_opt_pwr_ne__init
                     (Axos__LowRxOptPwrNe         *message)
{
  static const Axos__LowRxOptPwrNe init_value = AXOS__LOW_RX_OPT_PWR_NE__INIT;
  *message = init_value;
}
size_t axos__low_rx_opt_pwr_ne__get_packed_size
                     (const Axos__LowRxOptPwrNe *message)
{
  assert(message->base.descriptor == &axos__low_rx_opt_pwr_ne__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t axos__low_rx_opt_pwr_ne__pack
                     (const Axos__LowRxOptPwrNe *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &axos__low_rx_opt_pwr_ne__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t axos__low_rx_opt_pwr_ne__pack_to_buffer
                     (const Axos__LowRxOptPwrNe *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &axos__low_rx_opt_pwr_ne__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Axos__LowRxOptPwrNe *
       axos__low_rx_opt_pwr_ne__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Axos__LowRxOptPwrNe *)
     protobuf_c_message_unpack (&axos__low_rx_opt_pwr_ne__descriptor,
                                allocator, len, data);
}
void   axos__low_rx_opt_pwr_ne__free_unpacked
                     (Axos__LowRxOptPwrNe *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &axos__low_rx_opt_pwr_ne__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   axos__ntp_server_reachability__init
                     (Axos__NtpServerReachability         *message)
{
  static const Axos__NtpServerReachability init_value = AXOS__NTP_SERVER_REACHABILITY__INIT;
  *message = init_value;
}
size_t axos__ntp_server_reachability__get_packed_size
                     (const Axos__NtpServerReachability *message)
{
  assert(message->base.descriptor == &axos__ntp_server_reachability__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t axos__ntp_server_reachability__pack
                     (const Axos__NtpServerReachability *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &axos__ntp_server_reachability__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t axos__ntp_server_reachability__pack_to_buffer
                     (const Axos__NtpServerReachability *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &axos__ntp_server_reachability__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Axos__NtpServerReachability *
       axos__ntp_server_reachability__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Axos__NtpServerReachability *)
     protobuf_c_message_unpack (&axos__ntp_server_reachability__descriptor,
                                allocator, len, data);
}
void   axos__ntp_server_reachability__free_unpacked
                     (Axos__NtpServerReachability *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &axos__ntp_server_reachability__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   axos__ntp_server_reachability_clear__init
                     (Axos__NtpServerReachabilityClear         *message)
{
  static const Axos__NtpServerReachabilityClear init_value = AXOS__NTP_SERVER_REACHABILITY_CLEAR__INIT;
  *message = init_value;
}
size_t axos__ntp_server_reachability_clear__get_packed_size
                     (const Axos__NtpServerReachabilityClear *message)
{
  assert(message->base.descriptor == &axos__ntp_server_reachability_clear__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t axos__ntp_server_reachability_clear__pack
                     (const Axos__NtpServerReachabilityClear *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &axos__ntp_server_reachability_clear__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t axos__ntp_server_reachability_clear__pack_to_buffer
                     (const Axos__NtpServerReachabilityClear *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &axos__ntp_server_reachability_clear__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Axos__NtpServerReachabilityClear *
       axos__ntp_server_reachability_clear__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Axos__NtpServerReachabilityClear *)
     protobuf_c_message_unpack (&axos__ntp_server_reachability_clear__descriptor,
                                allocator, len, data);
}
void   axos__ntp_server_reachability_clear__free_unpacked
                     (Axos__NtpServerReachabilityClear *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &axos__ntp_server_reachability_clear__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   axos__dhcp_lease_establishment__init
                     (Axos__DhcpLeaseEstablishment         *message)
{
  static const Axos__DhcpLeaseEstablishment init_value = AXOS__DHCP_LEASE_ESTABLISHMENT__INIT;
  *message = init_value;
}
size_t axos__dhcp_lease_establishment__get_packed_size
                     (const Axos__DhcpLeaseEstablishment *message)
{
  assert(message->base.descriptor == &axos__dhcp_lease_establishment__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t axos__dhcp_lease_establishment__pack
                     (const Axos__DhcpLeaseEstablishment *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &axos__dhcp_lease_establishment__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t axos__dhcp_lease_establishment__pack_to_buffer
                     (const Axos__DhcpLeaseEstablishment *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &axos__dhcp_lease_establishment__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Axos__DhcpLeaseEstablishment *
       axos__dhcp_lease_establishment__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Axos__DhcpLeaseEstablishment *)
     protobuf_c_message_unpack (&axos__dhcp_lease_establishment__descriptor,
                                allocator, len, data);
}
void   axos__dhcp_lease_establishment__free_unpacked
                     (Axos__DhcpLeaseEstablishment *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &axos__dhcp_lease_establishment__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   axos__dhcp_lease_termination__init
                     (Axos__DhcpLeaseTermination         *message)
{
  static const Axos__DhcpLeaseTermination init_value = AXOS__DHCP_LEASE_TERMINATION__INIT;
  *message = init_value;
}
size_t axos__dhcp_lease_termination__get_packed_size
                     (const Axos__DhcpLeaseTermination *message)
{
  assert(message->base.descriptor == &axos__dhcp_lease_termination__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t axos__dhcp_lease_termination__pack
                     (const Axos__DhcpLeaseTermination *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &axos__dhcp_lease_termination__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t axos__dhcp_lease_termination__pack_to_buffer
                     (const Axos__DhcpLeaseTermination *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &axos__dhcp_lease_termination__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Axos__DhcpLeaseTermination *
       axos__dhcp_lease_termination__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Axos__DhcpLeaseTermination *)
     protobuf_c_message_unpack (&axos__dhcp_lease_termination__descriptor,
                                allocator, len, data);
}
void   axos__dhcp_lease_termination__free_unpacked
                     (Axos__DhcpLeaseTermination *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &axos__dhcp_lease_termination__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   axos__loss_of_pon__init
                     (Axos__LossOfPon         *message)
{
  static const Axos__LossOfPon init_value = AXOS__LOSS_OF_PON__INIT;
  *message = init_value;
}
size_t axos__loss_of_pon__get_packed_size
                     (const Axos__LossOfPon *message)
{
  assert(message->base.descriptor == &axos__loss_of_pon__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t axos__loss_of_pon__pack
                     (const Axos__LossOfPon *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &axos__loss_of_pon__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t axos__loss_of_pon__pack_to_buffer
                     (const Axos__LossOfPon *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &axos__loss_of_pon__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Axos__LossOfPon *
       axos__loss_of_pon__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Axos__LossOfPon *)
     protobuf_c_message_unpack (&axos__loss_of_pon__descriptor,
                                allocator, len, data);
}
void   axos__loss_of_pon__free_unpacked
                     (Axos__LossOfPon *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &axos__loss_of_pon__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   axos__loss_of_pon_clear__init
                     (Axos__LossOfPonClear         *message)
{
  static const Axos__LossOfPonClear init_value = AXOS__LOSS_OF_PON_CLEAR__INIT;
  *message = init_value;
}
size_t axos__loss_of_pon_clear__get_packed_size
                     (const Axos__LossOfPonClear *message)
{
  assert(message->base.descriptor == &axos__loss_of_pon_clear__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t axos__loss_of_pon_clear__pack
                     (const Axos__LossOfPonClear *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &axos__loss_of_pon_clear__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t axos__loss_of_pon_clear__pack_to_buffer
                     (const Axos__LossOfPonClear *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &axos__loss_of_pon_clear__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Axos__LossOfPonClear *
       axos__loss_of_pon_clear__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Axos__LossOfPonClear *)
     protobuf_c_message_unpack (&axos__loss_of_pon_clear__descriptor,
                                allocator, len, data);
}
void   axos__loss_of_pon_clear__free_unpacked
                     (Axos__LossOfPonClear *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &axos__loss_of_pon_clear__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   axos__omci_comm_fail__init
                     (Axos__OmciCommFail         *message)
{
  static const Axos__OmciCommFail init_value = AXOS__OMCI_COMM_FAIL__INIT;
  *message = init_value;
}
size_t axos__omci_comm_fail__get_packed_size
                     (const Axos__OmciCommFail *message)
{
  assert(message->base.descriptor == &axos__omci_comm_fail__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t axos__omci_comm_fail__pack
                     (const Axos__OmciCommFail *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &axos__omci_comm_fail__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t axos__omci_comm_fail__pack_to_buffer
                     (const Axos__OmciCommFail *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &axos__omci_comm_fail__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Axos__OmciCommFail *
       axos__omci_comm_fail__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Axos__OmciCommFail *)
     protobuf_c_message_unpack (&axos__omci_comm_fail__descriptor,
                                allocator, len, data);
}
void   axos__omci_comm_fail__free_unpacked
                     (Axos__OmciCommFail *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &axos__omci_comm_fail__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   axos__ont_sw_mismatch__init
                     (Axos__OntSwMismatch         *message)
{
  static const Axos__OntSwMismatch init_value = AXOS__ONT_SW_MISMATCH__INIT;
  *message = init_value;
}
size_t axos__ont_sw_mismatch__get_packed_size
                     (const Axos__OntSwMismatch *message)
{
  assert(message->base.descriptor == &axos__ont_sw_mismatch__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t axos__ont_sw_mismatch__pack
                     (const Axos__OntSwMismatch *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &axos__ont_sw_mismatch__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t axos__ont_sw_mismatch__pack_to_buffer
                     (const Axos__OntSwMismatch *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &axos__ont_sw_mismatch__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Axos__OntSwMismatch *
       axos__ont_sw_mismatch__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Axos__OntSwMismatch *)
     protobuf_c_message_unpack (&axos__ont_sw_mismatch__descriptor,
                                allocator, len, data);
}
void   axos__ont_sw_mismatch__free_unpacked
                     (Axos__OntSwMismatch *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &axos__ont_sw_mismatch__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   axos__ont_sw_mismatch_clear__init
                     (Axos__OntSwMismatchClear         *message)
{
  static const Axos__OntSwMismatchClear init_value = AXOS__ONT_SW_MISMATCH_CLEAR__INIT;
  *message = init_value;
}
size_t axos__ont_sw_mismatch_clear__get_packed_size
                     (const Axos__OntSwMismatchClear *message)
{
  assert(message->base.descriptor == &axos__ont_sw_mismatch_clear__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t axos__ont_sw_mismatch_clear__pack
                     (const Axos__OntSwMismatchClear *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &axos__ont_sw_mismatch_clear__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t axos__ont_sw_mismatch_clear__pack_to_buffer
                     (const Axos__OntSwMismatchClear *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &axos__ont_sw_mismatch_clear__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Axos__OntSwMismatchClear *
       axos__ont_sw_mismatch_clear__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Axos__OntSwMismatchClear *)
     protobuf_c_message_unpack (&axos__ont_sw_mismatch_clear__descriptor,
                                allocator, len, data);
}
void   axos__ont_sw_mismatch_clear__free_unpacked
                     (Axos__OntSwMismatchClear *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &axos__ont_sw_mismatch_clear__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   axos__ont_download_start__init
                     (Axos__OntDownloadStart         *message)
{
  static const Axos__OntDownloadStart init_value = AXOS__ONT_DOWNLOAD_START__INIT;
  *message = init_value;
}
size_t axos__ont_download_start__get_packed_size
                     (const Axos__OntDownloadStart *message)
{
  assert(message->base.descriptor == &axos__ont_download_start__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t axos__ont_download_start__pack
                     (const Axos__OntDownloadStart *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &axos__ont_download_start__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t axos__ont_download_start__pack_to_buffer
                     (const Axos__OntDownloadStart *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &axos__ont_download_start__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Axos__OntDownloadStart *
       axos__ont_download_start__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Axos__OntDownloadStart *)
     protobuf_c_message_unpack (&axos__ont_download_start__descriptor,
                                allocator, len, data);
}
void   axos__ont_download_start__free_unpacked
                     (Axos__OntDownloadStart *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &axos__ont_download_start__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   axos__ont_download_fail__init
                     (Axos__OntDownloadFail         *message)
{
  static const Axos__OntDownloadFail init_value = AXOS__ONT_DOWNLOAD_FAIL__INIT;
  *message = init_value;
}
size_t axos__ont_download_fail__get_packed_size
                     (const Axos__OntDownloadFail *message)
{
  assert(message->base.descriptor == &axos__ont_download_fail__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t axos__ont_download_fail__pack
                     (const Axos__OntDownloadFail *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &axos__ont_download_fail__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t axos__ont_download_fail__pack_to_buffer
                     (const Axos__OntDownloadFail *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &axos__ont_download_fail__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Axos__OntDownloadFail *
       axos__ont_download_fail__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Axos__OntDownloadFail *)
     protobuf_c_message_unpack (&axos__ont_download_fail__descriptor,
                                allocator, len, data);
}
void   axos__ont_download_fail__free_unpacked
                     (Axos__OntDownloadFail *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &axos__ont_download_fail__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor axos__ont_missing__field_descriptors[4] =
{
  {
    "event_time",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Axos__OntMissing, event_time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ont_id",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Axos__OntMissing, ont_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vendor_id",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Axos__OntMissing, vendor_id),
    &axos__vendor__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "serial_number",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Axos__OntMissing, serial_number),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned axos__ont_missing__field_indices_by_name[] = {
  0,   /* field[0] = event_time */
  1,   /* field[1] = ont_id */
  3,   /* field[3] = serial_number */
  2,   /* field[2] = vendor_id */
};
static const ProtobufCIntRange axos__ont_missing__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor axos__ont_missing__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "axos.ont_missing",
  "OntMissing",
  "Axos__OntMissing",
  "axos",
  sizeof(Axos__OntMissing),
  4,
  axos__ont_missing__field_descriptors,
  axos__ont_missing__field_indices_by_name,
  1,  axos__ont_missing__number_ranges,
  (ProtobufCMessageInit) axos__ont_missing__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor axos__ont_ds_sdber__field_descriptors[4] =
{
  {
    "event_time",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Axos__OntDsSdber, event_time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ont_id",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Axos__OntDsSdber, ont_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vendor_id",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Axos__OntDsSdber, vendor_id),
    &axos__vendor__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "serial_number",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Axos__OntDsSdber, serial_number),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned axos__ont_ds_sdber__field_indices_by_name[] = {
  0,   /* field[0] = event_time */
  1,   /* field[1] = ont_id */
  3,   /* field[3] = serial_number */
  2,   /* field[2] = vendor_id */
};
static const ProtobufCIntRange axos__ont_ds_sdber__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor axos__ont_ds_sdber__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "axos.ont_ds_sdber",
  "OntDsSdber",
  "Axos__OntDsSdber",
  "axos",
  sizeof(Axos__OntDsSdber),
  4,
  axos__ont_ds_sdber__field_descriptors,
  axos__ont_ds_sdber__field_indices_by_name,
  1,  axos__ont_ds_sdber__number_ranges,
  (ProtobufCMessageInit) axos__ont_ds_sdber__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor axos__ont_us_sdber__field_descriptors[4] =
{
  {
    "event_time",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Axos__OntUsSdber, event_time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ont_id",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Axos__OntUsSdber, ont_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vendor_id",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Axos__OntUsSdber, vendor_id),
    &axos__vendor__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "serial_number",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Axos__OntUsSdber, serial_number),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned axos__ont_us_sdber__field_indices_by_name[] = {
  0,   /* field[0] = event_time */
  1,   /* field[1] = ont_id */
  3,   /* field[3] = serial_number */
  2,   /* field[2] = vendor_id */
};
static const ProtobufCIntRange axos__ont_us_sdber__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor axos__ont_us_sdber__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "axos.ont_us_sdber",
  "OntUsSdber",
  "Axos__OntUsSdber",
  "axos",
  sizeof(Axos__OntUsSdber),
  4,
  axos__ont_us_sdber__field_descriptors,
  axos__ont_us_sdber__field_indices_by_name,
  1,  axos__ont_us_sdber__number_ranges,
  (ProtobufCMessageInit) axos__ont_us_sdber__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor axos__ont_arrival__field_descriptors[4] =
{
  {
    "event_time",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Axos__OntArrival, event_time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ont_id",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Axos__OntArrival, ont_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vendor_id",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Axos__OntArrival, vendor_id),
    &axos__vendor__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "serial_number",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Axos__OntArrival, serial_number),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned axos__ont_arrival__field_indices_by_name[] = {
  0,   /* field[0] = event_time */
  1,   /* field[1] = ont_id */
  3,   /* field[3] = serial_number */
  2,   /* field[2] = vendor_id */
};
static const ProtobufCIntRange axos__ont_arrival__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor axos__ont_arrival__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "axos.ont_arrival",
  "OntArrival",
  "Axos__OntArrival",
  "axos",
  sizeof(Axos__OntArrival),
  4,
  axos__ont_arrival__field_descriptors,
  axos__ont_arrival__field_indices_by_name,
  1,  axos__ont_arrival__number_ranges,
  (ProtobufCMessageInit) axos__ont_arrival__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor axos__ont_departure__field_descriptors[4] =
{
  {
    "event_time",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Axos__OntDeparture, event_time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ont_id",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Axos__OntDeparture, ont_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vendor_id",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Axos__OntDeparture, vendor_id),
    &axos__vendor__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "serial_number",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Axos__OntDeparture, serial_number),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned axos__ont_departure__field_indices_by_name[] = {
  0,   /* field[0] = event_time */
  1,   /* field[1] = ont_id */
  3,   /* field[3] = serial_number */
  2,   /* field[2] = vendor_id */
};
static const ProtobufCIntRange axos__ont_departure__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor axos__ont_departure__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "axos.ont_departure",
  "OntDeparture",
  "Axos__OntDeparture",
  "axos",
  sizeof(Axos__OntDeparture),
  4,
  axos__ont_departure__field_descriptors,
  axos__ont_departure__field_indices_by_name,
  1,  axos__ont_departure__number_ranges,
  (ProtobufCMessageInit) axos__ont_departure__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor axos__user_login__field_descriptors[6] =
{
  {
    "event_time",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Axos__UserLogin, event_time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "system_name",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Axos__UserLogin, system_name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "system_ip",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FIXED32,
    0,   /* quantifier_offset */
    offsetof(Axos__UserLogin, system_ip),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "session_ip",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FIXED32,
    0,   /* quantifier_offset */
    offsetof(Axos__UserLogin, session_ip),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "session_id",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Axos__UserLogin, session_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "user_name",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Axos__UserLogin, user_name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned axos__user_login__field_indices_by_name[] = {
  0,   /* field[0] = event_time */
  4,   /* field[4] = session_id */
  3,   /* field[3] = session_ip */
  2,   /* field[2] = system_ip */
  1,   /* field[1] = system_name */
  5,   /* field[5] = user_name */
};
static const ProtobufCIntRange axos__user_login__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor axos__user_login__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "axos.user_login",
  "UserLogin",
  "Axos__UserLogin",
  "axos",
  sizeof(Axos__UserLogin),
  6,
  axos__user_login__field_descriptors,
  axos__user_login__field_indices_by_name,
  1,  axos__user_login__number_ranges,
  (ProtobufCMessageInit) axos__user_login__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor axos__user_logout__field_descriptors[6] =
{
  {
    "event_time",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Axos__UserLogout, event_time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "system_name",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Axos__UserLogout, system_name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "system_ip",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FIXED32,
    0,   /* quantifier_offset */
    offsetof(Axos__UserLogout, system_ip),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "session_ip",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FIXED32,
    0,   /* quantifier_offset */
    offsetof(Axos__UserLogout, session_ip),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "session_id",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Axos__UserLogout, session_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "user_name",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Axos__UserLogout, user_name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned axos__user_logout__field_indices_by_name[] = {
  0,   /* field[0] = event_time */
  4,   /* field[4] = session_id */
  3,   /* field[3] = session_ip */
  2,   /* field[2] = system_ip */
  1,   /* field[1] = system_name */
  5,   /* field[5] = user_name */
};
static const ProtobufCIntRange axos__user_logout__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor axos__user_logout__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "axos.user_logout",
  "UserLogout",
  "Axos__UserLogout",
  "axos",
  sizeof(Axos__UserLogout),
  6,
  axos__user_logout__field_descriptors,
  axos__user_logout__field_indices_by_name,
  1,  axos__user_logout__number_ranges,
  (ProtobufCMessageInit) axos__user_logout__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor axos__ont_eth_down__field_descriptors[5] =
{
  {
    "event_time",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Axos__OntEthDown, event_time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ont_id",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Axos__OntEthDown, ont_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "port",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Axos__OntEthDown, port),
    &axos__eth_port__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vendor_id",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Axos__OntEthDown, vendor_id),
    &axos__vendor__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "serial_number",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Axos__OntEthDown, serial_number),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned axos__ont_eth_down__field_indices_by_name[] = {
  0,   /* field[0] = event_time */
  1,   /* field[1] = ont_id */
  2,   /* field[2] = port */
  4,   /* field[4] = serial_number */
  3,   /* field[3] = vendor_id */
};
static const ProtobufCIntRange axos__ont_eth_down__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor axos__ont_eth_down__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "axos.ont_eth_down",
  "OntEthDown",
  "Axos__OntEthDown",
  "axos",
  sizeof(Axos__OntEthDown),
  5,
  axos__ont_eth_down__field_descriptors,
  axos__ont_eth_down__field_indices_by_name,
  1,  axos__ont_eth_down__number_ranges,
  (ProtobufCMessageInit) axos__ont_eth_down__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor axos__ont_eth_down_clear__field_descriptors[5] =
{
  {
    "event_time",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Axos__OntEthDownClear, event_time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ont_id",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Axos__OntEthDownClear, ont_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "port",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Axos__OntEthDownClear, port),
    &axos__eth_port__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vendor_id",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Axos__OntEthDownClear, vendor_id),
    &axos__vendor__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "serial_number",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Axos__OntEthDownClear, serial_number),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned axos__ont_eth_down_clear__field_indices_by_name[] = {
  0,   /* field[0] = event_time */
  1,   /* field[1] = ont_id */
  2,   /* field[2] = port */
  4,   /* field[4] = serial_number */
  3,   /* field[3] = vendor_id */
};
static const ProtobufCIntRange axos__ont_eth_down_clear__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor axos__ont_eth_down_clear__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "axos.ont_eth_down_clear",
  "OntEthDownClear",
  "Axos__OntEthDownClear",
  "axos",
  sizeof(Axos__OntEthDownClear),
  5,
  axos__ont_eth_down_clear__field_descriptors,
  axos__ont_eth_down_clear__field_indices_by_name,
  1,  axos__ont_eth_down_clear__number_ranges,
  (ProtobufCMessageInit) axos__ont_eth_down_clear__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor axos__ont_dying_gasp__field_descriptors[4] =
{
  {
    "event_time",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Axos__OntDyingGasp, event_time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ont_id",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Axos__OntDyingGasp, ont_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vendor_id",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Axos__OntDyingGasp, vendor_id),
    &axos__vendor__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "serial_number",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Axos__OntDyingGasp, serial_number),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned axos__ont_dying_gasp__field_indices_by_name[] = {
  0,   /* field[0] = event_time */
  1,   /* field[1] = ont_id */
  3,   /* field[3] = serial_number */
  2,   /* field[2] = vendor_id */
};
static const ProtobufCIntRange axos__ont_dying_gasp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor axos__ont_dying_gasp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "axos.ont_dying_gasp",
  "OntDyingGasp",
  "Axos__OntDyingGasp",
  "axos",
  sizeof(Axos__OntDyingGasp),
  4,
  axos__ont_dying_gasp__field_descriptors,
  axos__ont_dying_gasp__field_indices_by_name,
  1,  axos__ont_dying_gasp__number_ranges,
  (ProtobufCMessageInit) axos__ont_dying_gasp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor axos__ont_dying_gasp_clear__field_descriptors[4] =
{
  {
    "event_time",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Axos__OntDyingGaspClear, event_time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ont_id",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Axos__OntDyingGaspClear, ont_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vendor_id",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Axos__OntDyingGaspClear, vendor_id),
    &axos__vendor__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "serial_number",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Axos__OntDyingGaspClear, serial_number),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned axos__ont_dying_gasp_clear__field_indices_by_name[] = {
  0,   /* field[0] = event_time */
  1,   /* field[1] = ont_id */
  3,   /* field[3] = serial_number */
  2,   /* field[2] = vendor_id */
};
static const ProtobufCIntRange axos__ont_dying_gasp_clear__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor axos__ont_dying_gasp_clear__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "axos.ont_dying_gasp_clear",
  "OntDyingGaspClear",
  "Axos__OntDyingGaspClear",
  "axos",
  sizeof(Axos__OntDyingGaspClear),
  4,
  axos__ont_dying_gasp_clear__field_descriptors,
  axos__ont_dying_gasp_clear__field_indices_by_name,
  1,  axos__ont_dying_gasp_clear__number_ranges,
  (ProtobufCMessageInit) axos__ont_dying_gasp_clear__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor axos__low_rx_opt_pwr_ne__field_descriptors[4] =
{
  {
    "event_time",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Axos__LowRxOptPwrNe, event_time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ont_id",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Axos__LowRxOptPwrNe, ont_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vendor_id",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Axos__LowRxOptPwrNe, vendor_id),
    &axos__vendor__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "serial_number",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Axos__LowRxOptPwrNe, serial_number),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned axos__low_rx_opt_pwr_ne__field_indices_by_name[] = {
  0,   /* field[0] = event_time */
  1,   /* field[1] = ont_id */
  3,   /* field[3] = serial_number */
  2,   /* field[2] = vendor_id */
};
static const ProtobufCIntRange axos__low_rx_opt_pwr_ne__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor axos__low_rx_opt_pwr_ne__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "axos.low_rx_opt_pwr_ne",
  "LowRxOptPwrNe",
  "Axos__LowRxOptPwrNe",
  "axos",
  sizeof(Axos__LowRxOptPwrNe),
  4,
  axos__low_rx_opt_pwr_ne__field_descriptors,
  axos__low_rx_opt_pwr_ne__field_indices_by_name,
  1,  axos__low_rx_opt_pwr_ne__number_ranges,
  (ProtobufCMessageInit) axos__low_rx_opt_pwr_ne__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor axos__ntp_server_reachability__field_descriptors[3] =
{
  {
    "event_time",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Axos__NtpServerReachability, event_time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "system_name",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Axos__NtpServerReachability, system_name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "system_ip",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FIXED32,
    0,   /* quantifier_offset */
    offsetof(Axos__NtpServerReachability, system_ip),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned axos__ntp_server_reachability__field_indices_by_name[] = {
  0,   /* field[0] = event_time */
  2,   /* field[2] = system_ip */
  1,   /* field[1] = system_name */
};
static const ProtobufCIntRange axos__ntp_server_reachability__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor axos__ntp_server_reachability__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "axos.ntp_server_reachability",
  "NtpServerReachability",
  "Axos__NtpServerReachability",
  "axos",
  sizeof(Axos__NtpServerReachability),
  3,
  axos__ntp_server_reachability__field_descriptors,
  axos__ntp_server_reachability__field_indices_by_name,
  1,  axos__ntp_server_reachability__number_ranges,
  (ProtobufCMessageInit) axos__ntp_server_reachability__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor axos__ntp_server_reachability_clear__field_descriptors[3] =
{
  {
    "event_time",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Axos__NtpServerReachabilityClear, event_time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "system_name",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Axos__NtpServerReachabilityClear, system_name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "system_ip",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FIXED32,
    0,   /* quantifier_offset */
    offsetof(Axos__NtpServerReachabilityClear, system_ip),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned axos__ntp_server_reachability_clear__field_indices_by_name[] = {
  0,   /* field[0] = event_time */
  2,   /* field[2] = system_ip */
  1,   /* field[1] = system_name */
};
static const ProtobufCIntRange axos__ntp_server_reachability_clear__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor axos__ntp_server_reachability_clear__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "axos.ntp_server_reachability_clear",
  "NtpServerReachabilityClear",
  "Axos__NtpServerReachabilityClear",
  "axos",
  sizeof(Axos__NtpServerReachabilityClear),
  3,
  axos__ntp_server_reachability_clear__field_descriptors,
  axos__ntp_server_reachability_clear__field_indices_by_name,
  1,  axos__ntp_server_reachability_clear__number_ranges,
  (ProtobufCMessageInit) axos__ntp_server_reachability_clear__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor axos__dhcp_lease_establishment__field_descriptors[7] =
{
  {
    "event_time",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Axos__DhcpLeaseEstablishment, event_time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ip",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FIXED32,
    0,   /* quantifier_offset */
    offsetof(Axos__DhcpLeaseEstablishment, ip),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mac",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Axos__DhcpLeaseEstablishment, mac),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ont_id",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Axos__DhcpLeaseEstablishment, ont_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "port",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Axos__DhcpLeaseEstablishment, port),
    &axos__eth_port__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vlan_id",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Axos__DhcpLeaseEstablishment, vlan_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "c_vlan_id",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Axos__DhcpLeaseEstablishment, c_vlan_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned axos__dhcp_lease_establishment__field_indices_by_name[] = {
  6,   /* field[6] = c_vlan_id */
  0,   /* field[0] = event_time */
  1,   /* field[1] = ip */
  2,   /* field[2] = mac */
  3,   /* field[3] = ont_id */
  4,   /* field[4] = port */
  5,   /* field[5] = vlan_id */
};
static const ProtobufCIntRange axos__dhcp_lease_establishment__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor axos__dhcp_lease_establishment__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "axos.dhcp_lease_establishment",
  "DhcpLeaseEstablishment",
  "Axos__DhcpLeaseEstablishment",
  "axos",
  sizeof(Axos__DhcpLeaseEstablishment),
  7,
  axos__dhcp_lease_establishment__field_descriptors,
  axos__dhcp_lease_establishment__field_indices_by_name,
  1,  axos__dhcp_lease_establishment__number_ranges,
  (ProtobufCMessageInit) axos__dhcp_lease_establishment__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor axos__dhcp_lease_termination__field_descriptors[7] =
{
  {
    "event_time",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Axos__DhcpLeaseTermination, event_time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ip",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FIXED32,
    0,   /* quantifier_offset */
    offsetof(Axos__DhcpLeaseTermination, ip),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mac",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Axos__DhcpLeaseTermination, mac),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ont_id",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Axos__DhcpLeaseTermination, ont_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "port",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Axos__DhcpLeaseTermination, port),
    &axos__eth_port__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vlan_id",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Axos__DhcpLeaseTermination, vlan_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "c_vlan_id",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Axos__DhcpLeaseTermination, c_vlan_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned axos__dhcp_lease_termination__field_indices_by_name[] = {
  6,   /* field[6] = c_vlan_id */
  0,   /* field[0] = event_time */
  1,   /* field[1] = ip */
  2,   /* field[2] = mac */
  3,   /* field[3] = ont_id */
  4,   /* field[4] = port */
  5,   /* field[5] = vlan_id */
};
static const ProtobufCIntRange axos__dhcp_lease_termination__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor axos__dhcp_lease_termination__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "axos.dhcp_lease_termination",
  "DhcpLeaseTermination",
  "Axos__DhcpLeaseTermination",
  "axos",
  sizeof(Axos__DhcpLeaseTermination),
  7,
  axos__dhcp_lease_termination__field_descriptors,
  axos__dhcp_lease_termination__field_indices_by_name,
  1,  axos__dhcp_lease_termination__number_ranges,
  (ProtobufCMessageInit) axos__dhcp_lease_termination__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor axos__loss_of_pon__field_descriptors[6] =
{
  {
    "event_time",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Axos__LossOfPon, event_time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "system_name",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Axos__LossOfPon, system_name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "system_ip",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FIXED32,
    0,   /* quantifier_offset */
    offsetof(Axos__LossOfPon, system_ip),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "shelf_id",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Axos__LossOfPon, shelf_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "slot_id",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Axos__LossOfPon, slot_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "port",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Axos__LossOfPon, port),
    &axos__pon_port__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned axos__loss_of_pon__field_indices_by_name[] = {
  0,   /* field[0] = event_time */
  5,   /* field[5] = port */
  3,   /* field[3] = shelf_id */
  4,   /* field[4] = slot_id */
  2,   /* field[2] = system_ip */
  1,   /* field[1] = system_name */
};
static const ProtobufCIntRange axos__loss_of_pon__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor axos__loss_of_pon__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "axos.loss_of_pon",
  "LossOfPon",
  "Axos__LossOfPon",
  "axos",
  sizeof(Axos__LossOfPon),
  6,
  axos__loss_of_pon__field_descriptors,
  axos__loss_of_pon__field_indices_by_name,
  1,  axos__loss_of_pon__number_ranges,
  (ProtobufCMessageInit) axos__loss_of_pon__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor axos__loss_of_pon_clear__field_descriptors[6] =
{
  {
    "event_time",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Axos__LossOfPonClear, event_time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "system_name",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Axos__LossOfPonClear, system_name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "system_ip",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FIXED32,
    0,   /* quantifier_offset */
    offsetof(Axos__LossOfPonClear, system_ip),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "shelf_id",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Axos__LossOfPonClear, shelf_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "slot_id",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Axos__LossOfPonClear, slot_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "port",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Axos__LossOfPonClear, port),
    &axos__pon_port__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned axos__loss_of_pon_clear__field_indices_by_name[] = {
  0,   /* field[0] = event_time */
  5,   /* field[5] = port */
  3,   /* field[3] = shelf_id */
  4,   /* field[4] = slot_id */
  2,   /* field[2] = system_ip */
  1,   /* field[1] = system_name */
};
static const ProtobufCIntRange axos__loss_of_pon_clear__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor axos__loss_of_pon_clear__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "axos.loss_of_pon_clear",
  "LossOfPonClear",
  "Axos__LossOfPonClear",
  "axos",
  sizeof(Axos__LossOfPonClear),
  6,
  axos__loss_of_pon_clear__field_descriptors,
  axos__loss_of_pon_clear__field_indices_by_name,
  1,  axos__loss_of_pon_clear__number_ranges,
  (ProtobufCMessageInit) axos__loss_of_pon_clear__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor axos__omci_comm_fail__field_descriptors[4] =
{
  {
    "event_time",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Axos__OmciCommFail, event_time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ont_id",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Axos__OmciCommFail, ont_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vendor_id",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Axos__OmciCommFail, vendor_id),
    &axos__vendor__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "serial_number",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Axos__OmciCommFail, serial_number),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned axos__omci_comm_fail__field_indices_by_name[] = {
  0,   /* field[0] = event_time */
  1,   /* field[1] = ont_id */
  3,   /* field[3] = serial_number */
  2,   /* field[2] = vendor_id */
};
static const ProtobufCIntRange axos__omci_comm_fail__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor axos__omci_comm_fail__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "axos.omci_comm_fail",
  "OmciCommFail",
  "Axos__OmciCommFail",
  "axos",
  sizeof(Axos__OmciCommFail),
  4,
  axos__omci_comm_fail__field_descriptors,
  axos__omci_comm_fail__field_indices_by_name,
  1,  axos__omci_comm_fail__number_ranges,
  (ProtobufCMessageInit) axos__omci_comm_fail__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor axos__ont_sw_mismatch__field_descriptors[4] =
{
  {
    "event_time",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Axos__OntSwMismatch, event_time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ont_id",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Axos__OntSwMismatch, ont_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vendor_id",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Axos__OntSwMismatch, vendor_id),
    &axos__vendor__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "serial_number",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Axos__OntSwMismatch, serial_number),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned axos__ont_sw_mismatch__field_indices_by_name[] = {
  0,   /* field[0] = event_time */
  1,   /* field[1] = ont_id */
  3,   /* field[3] = serial_number */
  2,   /* field[2] = vendor_id */
};
static const ProtobufCIntRange axos__ont_sw_mismatch__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor axos__ont_sw_mismatch__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "axos.ont_sw_mismatch",
  "OntSwMismatch",
  "Axos__OntSwMismatch",
  "axos",
  sizeof(Axos__OntSwMismatch),
  4,
  axos__ont_sw_mismatch__field_descriptors,
  axos__ont_sw_mismatch__field_indices_by_name,
  1,  axos__ont_sw_mismatch__number_ranges,
  (ProtobufCMessageInit) axos__ont_sw_mismatch__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor axos__ont_sw_mismatch_clear__field_descriptors[4] =
{
  {
    "event_time",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Axos__OntSwMismatchClear, event_time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ont_id",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Axos__OntSwMismatchClear, ont_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vendor_id",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Axos__OntSwMismatchClear, vendor_id),
    &axos__vendor__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "serial_number",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Axos__OntSwMismatchClear, serial_number),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned axos__ont_sw_mismatch_clear__field_indices_by_name[] = {
  0,   /* field[0] = event_time */
  1,   /* field[1] = ont_id */
  3,   /* field[3] = serial_number */
  2,   /* field[2] = vendor_id */
};
static const ProtobufCIntRange axos__ont_sw_mismatch_clear__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor axos__ont_sw_mismatch_clear__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "axos.ont_sw_mismatch_clear",
  "OntSwMismatchClear",
  "Axos__OntSwMismatchClear",
  "axos",
  sizeof(Axos__OntSwMismatchClear),
  4,
  axos__ont_sw_mismatch_clear__field_descriptors,
  axos__ont_sw_mismatch_clear__field_indices_by_name,
  1,  axos__ont_sw_mismatch_clear__number_ranges,
  (ProtobufCMessageInit) axos__ont_sw_mismatch_clear__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor axos__ont_download_start__field_descriptors[4] =
{
  {
    "event_time",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Axos__OntDownloadStart, event_time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ont_id",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Axos__OntDownloadStart, ont_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vendor_id",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Axos__OntDownloadStart, vendor_id),
    &axos__vendor__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "serial_number",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Axos__OntDownloadStart, serial_number),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned axos__ont_download_start__field_indices_by_name[] = {
  0,   /* field[0] = event_time */
  1,   /* field[1] = ont_id */
  3,   /* field[3] = serial_number */
  2,   /* field[2] = vendor_id */
};
static const ProtobufCIntRange axos__ont_download_start__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor axos__ont_download_start__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "axos.ont_download_start",
  "OntDownloadStart",
  "Axos__OntDownloadStart",
  "axos",
  sizeof(Axos__OntDownloadStart),
  4,
  axos__ont_download_start__field_descriptors,
  axos__ont_download_start__field_indices_by_name,
  1,  axos__ont_download_start__number_ranges,
  (ProtobufCMessageInit) axos__ont_download_start__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor axos__ont_download_fail__field_descriptors[4] =
{
  {
    "event_time",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Axos__OntDownloadFail, event_time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ont_id",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Axos__OntDownloadFail, ont_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vendor_id",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Axos__OntDownloadFail, vendor_id),
    &axos__vendor__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "serial_number",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Axos__OntDownloadFail, serial_number),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned axos__ont_download_fail__field_indices_by_name[] = {
  0,   /* field[0] = event_time */
  1,   /* field[1] = ont_id */
  3,   /* field[3] = serial_number */
  2,   /* field[2] = vendor_id */
};
static const ProtobufCIntRange axos__ont_download_fail__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor axos__ont_download_fail__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "axos.ont_download_fail",
  "OntDownloadFail",
  "Axos__OntDownloadFail",
  "axos",
  sizeof(Axos__OntDownloadFail),
  4,
  axos__ont_download_fail__field_descriptors,
  axos__ont_download_fail__field_indices_by_name,
  1,  axos__ont_download_fail__number_ranges,
  (ProtobufCMessageInit) axos__ont_download_fail__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue axos__vendor__enum_values_by_number[1] =
{
  { "CXNK", "AXOS__VENDOR__CXNK", 0 },
};
static const ProtobufCIntRange axos__vendor__value_ranges[] = {
{0, 0},{0, 1}
};
static const ProtobufCEnumValueIndex axos__vendor__enum_values_by_name[1] =
{
  { "CXNK", 0 },
};
const ProtobufCEnumDescriptor axos__vendor__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "axos.vendor",
  "vendor",
  "Axos__Vendor",
  "axos",
  1,
  axos__vendor__enum_values_by_number,
  1,
  axos__vendor__enum_values_by_name,
  1,
  axos__vendor__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue axos__eth_port__enum_values_by_number[4] =
{
  { "g1", "AXOS__ETH_PORT__g1", 0 },
  { "g2", "AXOS__ETH_PORT__g2", 1 },
  { "g3", "AXOS__ETH_PORT__g3", 2 },
  { "g4", "AXOS__ETH_PORT__g4", 3 },
};
static const ProtobufCIntRange axos__eth_port__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex axos__eth_port__enum_values_by_name[4] =
{
  { "g1", 0 },
  { "g2", 1 },
  { "g3", 2 },
  { "g4", 3 },
};
const ProtobufCEnumDescriptor axos__eth_port__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "axos.eth_port",
  "eth_port",
  "Axos__EthPort",
  "axos",
  4,
  axos__eth_port__enum_values_by_number,
  4,
  axos__eth_port__enum_values_by_name,
  1,
  axos__eth_port__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue axos__pon_port__enum_values_by_number[16] =
{
  { "gp1", "AXOS__PON_PORT__gp1", 0 },
  { "gp2", "AXOS__PON_PORT__gp2", 1 },
  { "gp3", "AXOS__PON_PORT__gp3", 2 },
  { "gp4", "AXOS__PON_PORT__gp4", 3 },
  { "gp5", "AXOS__PON_PORT__gp5", 4 },
  { "gp6", "AXOS__PON_PORT__gp6", 5 },
  { "gp7", "AXOS__PON_PORT__gp7", 6 },
  { "gp8", "AXOS__PON_PORT__gp8", 7 },
  { "gp9", "AXOS__PON_PORT__gp9", 8 },
  { "gp10", "AXOS__PON_PORT__gp10", 9 },
  { "gp11", "AXOS__PON_PORT__gp11", 10 },
  { "gp12", "AXOS__PON_PORT__gp12", 11 },
  { "gp13", "AXOS__PON_PORT__gp13", 12 },
  { "gp14", "AXOS__PON_PORT__gp14", 13 },
  { "gp15", "AXOS__PON_PORT__gp15", 14 },
  { "gp16", "AXOS__PON_PORT__gp16", 15 },
};
static const ProtobufCIntRange axos__pon_port__value_ranges[] = {
{0, 0},{0, 16}
};
static const ProtobufCEnumValueIndex axos__pon_port__enum_values_by_name[16] =
{
  { "gp1", 0 },
  { "gp10", 9 },
  { "gp11", 10 },
  { "gp12", 11 },
  { "gp13", 12 },
  { "gp14", 13 },
  { "gp15", 14 },
  { "gp16", 15 },
  { "gp2", 1 },
  { "gp3", 2 },
  { "gp4", 3 },
  { "gp5", 4 },
  { "gp6", 5 },
  { "gp7", 6 },
  { "gp8", 7 },
  { "gp9", 8 },
};
const ProtobufCEnumDescriptor axos__pon_port__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "axos.pon_port",
  "pon_port",
  "Axos__PonPort",
  "axos",
  16,
  axos__pon_port__enum_values_by_number,
  16,
  axos__pon_port__enum_values_by_name,
  1,
  axos__pon_port__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
