/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: objects.proto */

#ifndef PROTOBUF_C_objects_2eproto__INCLUDED
#define PROTOBUF_C_objects_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif




/* --- enums --- */

typedef enum _Objects {
  OBJECTS__ont_missing = 0,
  OBJECTS__ont_ds_sdber = 1,
  OBJECTS__ont_us_sdber = 2,
  OBJECTS__ont_arrival = 3,
  OBJECTS__ont_departure = 4,
  OBJECTS__user_login = 5,
  OBJECTS__user_logout = 6,
  OBJECTS__ont_eth_down = 7,
  OBJECTS__ont_ethernet_down_clear = 8,
  OBJECTS__ont_dying_gasp = 9,
  OBJECTS__ont_dying_gasp_clear = 10,
  OBJECTS__low_rx_opt_pwr_ne = 11,
  OBJECTS__ntp_server_reachability = 12,
  OBJECTS__ntp_server_reachability_clear = 13,
  OBJECTS__dhcp_lease_establishment = 14,
  OBJECTS__dhcp_lease_termination = 15,
  OBJECTS__loss_of_pon = 16,
  OBJECTS__loss_of_pon_clear = 17,
  OBJECTS__omci_comm_fail = 18,
  OBJECTS__ont_sw_mismatch = 19,
  OBJECTS__ont_sw_mismatch_clear = 20,
  OBJECTS__ont_download_start = 21,
  OBJECTS__ont_download_fail = 22
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(OBJECTS)
} Objects;

/* --- messages --- */

/* --- per-message closures --- */


/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    objects__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_objects_2eproto__INCLUDED */
