/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: objects.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "objects.pb-c.h"
static const ProtobufCEnumValue objects__enum_values_by_number[23] =
{
  { "ont_missing", "OBJECTS__ont_missing", 0 },
  { "ont_ds_sdber", "OBJECTS__ont_ds_sdber", 1 },
  { "ont_us_sdber", "OBJECTS__ont_us_sdber", 2 },
  { "ont_arrival", "OBJECTS__ont_arrival", 3 },
  { "ont_departure", "OBJECTS__ont_departure", 4 },
  { "user_login", "OBJECTS__user_login", 5 },
  { "user_logout", "OBJECTS__user_logout", 6 },
  { "ont_eth_down", "OBJECTS__ont_eth_down", 7 },
  { "ont_ethernet_down_clear", "OBJECTS__ont_ethernet_down_clear", 8 },
  { "ont_dying_gasp", "OBJECTS__ont_dying_gasp", 9 },
  { "ont_dying_gasp_clear", "OBJECTS__ont_dying_gasp_clear", 10 },
  { "low_rx_opt_pwr_ne", "OBJECTS__low_rx_opt_pwr_ne", 11 },
  { "ntp_server_reachability", "OBJECTS__ntp_server_reachability", 12 },
  { "ntp_server_reachability_clear", "OBJECTS__ntp_server_reachability_clear", 13 },
  { "dhcp_lease_establishment", "OBJECTS__dhcp_lease_establishment", 14 },
  { "dhcp_lease_termination", "OBJECTS__dhcp_lease_termination", 15 },
  { "loss_of_pon", "OBJECTS__loss_of_pon", 16 },
  { "loss_of_pon_clear", "OBJECTS__loss_of_pon_clear", 17 },
  { "omci_comm_fail", "OBJECTS__omci_comm_fail", 18 },
  { "ont_sw_mismatch", "OBJECTS__ont_sw_mismatch", 19 },
  { "ont_sw_mismatch_clear", "OBJECTS__ont_sw_mismatch_clear", 20 },
  { "ont_download_start", "OBJECTS__ont_download_start", 21 },
  { "ont_download_fail", "OBJECTS__ont_download_fail", 22 },
};
static const ProtobufCIntRange objects__value_ranges[] = {
{0, 0},{0, 23}
};
static const ProtobufCEnumValueIndex objects__enum_values_by_name[23] =
{
  { "dhcp_lease_establishment", 14 },
  { "dhcp_lease_termination", 15 },
  { "loss_of_pon", 16 },
  { "loss_of_pon_clear", 17 },
  { "low_rx_opt_pwr_ne", 11 },
  { "ntp_server_reachability", 12 },
  { "ntp_server_reachability_clear", 13 },
  { "omci_comm_fail", 18 },
  { "ont_arrival", 3 },
  { "ont_departure", 4 },
  { "ont_download_fail", 22 },
  { "ont_download_start", 21 },
  { "ont_ds_sdber", 1 },
  { "ont_dying_gasp", 9 },
  { "ont_dying_gasp_clear", 10 },
  { "ont_eth_down", 7 },
  { "ont_ethernet_down_clear", 8 },
  { "ont_missing", 0 },
  { "ont_sw_mismatch", 19 },
  { "ont_sw_mismatch_clear", 20 },
  { "ont_us_sdber", 2 },
  { "user_login", 5 },
  { "user_logout", 6 },
};
const ProtobufCEnumDescriptor objects__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "objects",
  "objects",
  "Objects",
  "",
  23,
  objects__enum_values_by_number,
  23,
  objects__enum_values_by_name,
  1,
  objects__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
